[package]
name = "ziggurat"
version = "0.0.1"
authors = []
edition = "2021"

[dependencies]
"aes" = "=0.9.0-pre.2"
"cbc" = "=0.2.0-pre.2"
"constant_time_eq" = "=0.3.1"
"hex-literal" = "=0.4.1"
"hex" = "=0.4.3"
"pcap-parser" = "=0.16.0"
"shellexpand" = "=3.1.0"
"inline_colorization" = "0.1.6"
derivative = "2.2.0"
crc_all = "0.2.2"
strum_macros = "0.26.4"

[[bin]]
name = "ziggurat-pcap"
path = "src/tools/dump_pcap.rs"

[dev-dependencies]
rand = "0.8.5"
